import {
  profile,
  company_name,
  language,
  locality,
  phone,
  email,
  website,
  max_members,
  payment_type_id,
  product_type_id,
  sale_type_id,
  manager_name,
  manager_surname,
  manager_email,
  manager_phone,
  manager_username,
  manager_password,
} from '../../validations';

export const signupTenantValdn = [
  profile,
  company_name,
  language,
  locality,
  phone,
  email,
  website,
  max_members,
  payment_type_id,
  product_type_id,
  sale_type_id,
  manager_name,
  manager_surname,
  manager_email,
  manager_phone,
  manager_username,
  manager_password,
];
